name: ssignup_login
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/img2.png
  image_dark: assets/img2.png
  fullscreen: true # Ensures fullscreen mode is enabled
  android_gravity: fill # Ensures the image fills the screen properly
  android_12:
    image: assets/img2.png
    icon_background_color: "#f7f6f1"

    image_dark: assets/img2.png
    fullscreen: true # Explicitly set fullscreen for Android 12+
    icon_background_color_dark: "#272727"


flutter:
  uses-material-design: true

  assets:
    - assets/img_1.png
    - assets/img2.png
